### ISSUE TITLE
Online Learning

### ISSUE THREAD

**Issue by prakashtewari** [ryanurbs/ExSTraCS_2.0#2]
Thank you for the brilliant package. I tried your XCS package as well and that was great for learning LCS setup. 

I want to implement something similar to ExSTraCS but in an online environment for a dataset having continuous variables and discrete phenotype (class). Please correct me if I am wrong on my understanding of 'online learning'. 

It basically represents learning over new instances which are not used in the initial training of the rule population. So, we can have more datapoints (instances) coming in future and using 'online learning' we can update the rule population that we generated initially in the first set of training. 

If this is correct, please can we have some test examples for understanding the implementation? I understand from the User guide, that it is still not tested fully, but some test examples would help.

**Comment by ryanurbs** [comment]
Hello,

Thank you for your interest in ExSTraCS. Your understanding of online learning seems correct.  Instead of have a finite set of previously obtained training instances, you obtain new training instances from an environment indefinitely. This type of learning invalidates some of the key operators built into ExSTraCS (that you should be aware of), this includes how we currently generate and use Expert Knowledge derived from Relief-based algorithms.  You would not be able to do this (at least as it is programmed now) if you want to do online learning.


Also could you please clarify what you mean by test examples?  Since ExSTraCS and my area of research study is not focused on 'online-learning' problems, we did not implement more than some quick options for online learning in ExSTraCS, and while we'd be glad to collaborate, we will not have time in the near future to extend this aspect of ExSTraCS to any great extent.

Sincerely,

Ryan Urbanowicz

________________________________

**Comment by prakashtewari** [comment]
Thanks a lot for the response. It definitely helps in clearing my understanding of online learning. 

I would like to collaborate in developing online learning solution further but I dont have well defined understanding of ExSTraCS algorithm yet, I am reading up on it. 

I had a detailed look at your XCS implementation [link](http://gbml.org/2010/03/24/python-lcs-implementations-xcs-ucs-mcs-for-snp-environment/), on top of which ExSTraCS is built. Using this I tried to build an online learning function (where, new instances from a stored dataset was being imported for updating the rule population - [link](https://github.com/prakashtewari/XCS-Implementation/blob/master/XCS.py) . I was thinking of implementing a similar solution in ExSTraCS. 

I have still not been able to understand the differences between XCS and ExSTraCS completely. But  it looks that XCS uses reinforcement learning when executing action and ExSTraCS does not use it? I will read up more on it and reach out to you again for clearing my understanding.

Many thanks for your help and time!
