### ISSUE TITLE
difference between mutisurf and surfstar ?

### ISSUE THREAD

**Issue by bbit8** [ryanurbs/ExSTraCS_2.0#4]
mutisurf code:
`        
       hit_proportion=count_hit_near/float(count_hit_near+count_miss_near)
        miss_proportion=count_miss_near/float(count_hit_near+count_miss_near)
            
        diff=diff_hit_near*miss_proportion+diff_miss_near*hit_proportion #applying weighting scheme to balance the scores 
        
        hit_proportion=count_hit_far/float(count_hit_far+count_miss_far)
        miss_proportion=count_miss_far/float(count_hit_far+count_miss_far)

        diff+=diff_hit_far*miss_proportion+diff_miss_far*hit_proportion #applying weighting scheme to balance the scores
`
near diff + far diff

surfstar code:
` if len(NN_near) > 0:
    ScoreList[j]+=evaluate_SURF(x,y,NN_near,j,inst,data,multiclass_map,maxInst)
  
if len(NN_far) > 0:
    ScoreList[j]-=evaluate_SURF(x,y,NN_far,j,inst,data,multiclass_map,maxInst)
`

near diff - far diff

Is this a bug or not?

**Comment by ryanurbs** [comment]
While looking at these parts of the code it looks like an error, these two were implemented by different people and the negation of 'fars' happens elsewhere in the multisurf code.  Of note, this is an older implementation of these methods, and the MultiSURF algorithm implemented here is actually called MultiSURF* (since it considers both near and far scoring).  Currently the algorithm called MultiSURF only uses 'near' scores. 

The paper explaining this is here: https://www.sciencedirect.com/science/article/pii/S1532046418301412

The most up to date implementation of these relief-based algorithms is available here as a scikit learn package: https://github.com/EpistasisLab/ReBATE

There is also a newer version of Exstracs being developed as a scikit package that uses the above ReBATE package to run MultiSURF, MultiSURF*, SURF, SURF*, etc., available here: https://github.com/UrbsLab/scikit-ExSTraCS

scikit-exstracs seems to be  functional but we are still confirming its fidelity with ExSTraCS 2.0 on more complex problems.
